services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend
 
  mongodb:
    image: mongo:8
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend


volumes:
  mongo-data:

networks:
  backend: